# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 403e148eff56268b45752e73edb15d6639ed396bf9ab7df7114009d5f986eadae5e868b6cc9d9a8f0d2341ea548df452ae199083a0bd8e5c843e8948d708bc24

test:
  secret_key_base: 90c08522a950a6c1d355e05269fa82dfa1e898efc6e61ebf89bdcc455c9ae0389da86b76c2c734cfe133080fe02e46db64d3e7f3af108b4c62d93b0efa8a243a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
